coverage:
  round: down
  bot: "codecov-io"
  status:
    project:
      default:
        target: 80%    # The overall project coverage must be at least 80%
        threshold: 1%  # Allow a 1% drop before failing
    patch:
      default:
        target: 80%   # New code in the PR must have 100% coverage