import React, { useState } from 'react'
import './foundry.css'

const TEMPLATES: Record<string, string> = {
  'TypeScript / Node': `# AGENTS.md — generated by Foundry

# Project overview
TypeScript project. Describe your project here.

# How to build & test
\`npm run build\` — compiles the project
\`npm test\` — runs the test suite
\`npm run lint\` — lints source files

# Architecture conventions
- Keep modules small and focused
- Write tests alongside implementation
- Avoid mutating shared state

# Critical rules
- Tests must accompany every new public function
- Never commit secrets or API keys
`,
  General: `# AGENTS.md — generated by Foundry

# Project overview
Describe your project here.

# How to build & test
Add your build and test commands here.

# Architecture conventions
Add your conventions here.

# Critical rules
Add your critical rules here.
`,
  Python: `# AGENTS.md — generated by Foundry

# Project overview
Python project. Describe your project here.

# How to build & test
\`pip install -e .\` — install in dev mode
\`pytest\` — run tests
\`ruff check .\` — lint

# Architecture conventions
- Use type hints throughout
- Keep functions pure where possible
- One module per concern

# Critical rules
- Tests required for all public functions
- Use virtual environments
`,
  Blank: '# AGENTS.md\n\n',
}

type SensorStatus = 'unchecked' | 'checking' | 'pass' | 'fail'

interface SensorRow {
  name: string
  command: string
  status: SensorStatus
}

interface Props {
  repoRoot: string
  onComplete: () => void
  onCancel: () => void
}

type Step = 'template' | 'agents-md' | 'sensors' | 'provider' | 'done'
const STEPS: Step[] = ['template', 'agents-md', 'sensors', 'provider', 'done']
const STEP_LABELS: Record<Step, string> = {
  template: 'Template',
  'agents-md': 'AGENTS.md',
  sensors: 'Sensors',
  provider: 'Provider',
  done: 'Done',
}

function invoke(channel: string, payload: unknown) {
  return window.electronAPI.extensionBridge.invoke(channel, payload) as Promise<
    Record<string, unknown>
  >
}

export function HarnessSetupWizard({ repoRoot, onComplete, onCancel }: Props) {
  const [step, setStep] = useState<Step>('template')
  const [selectedTemplate, setSelectedTemplate] = useState('TypeScript / Node')
  const [agentsMd, setAgentsMd] = useState(TEMPLATES['TypeScript / Node'])
  const [sensors, setSensors] = useState<SensorRow[]>([
    { name: 'lint', command: '', status: 'unchecked' },
    { name: 'test', command: '', status: 'unchecked' },
  ])
  const [provider, setProvider] = useState('claude')
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const stepIdx = STEPS.indexOf(step)

  function pickTemplate(name: string) {
    setSelectedTemplate(name)
    setAgentsMd(TEMPLATES[name] ?? '')
  }

  function updateSensor(i: number, field: 'name' | 'command', val: string) {
    setSensors((prev) =>
      prev.map((s, j) => (j === i ? { ...s, [field]: val, status: 'unchecked' } : s))
    )
  }

  async function checkSensor(i: number) {
    const s = sensors[i]
    if (!s.command.trim()) return
    setSensors((prev) => prev.map((r, j) => (j === i ? { ...r, status: 'checking' } : r)))
    try {
      const res = await invoke('foundry:sensor-run', {
        sensorName: s.name || `sensor-${i}`,
        command: s.command,
        workspaceRoot: repoRoot,
      })
      const pass = (res.result as { pass?: boolean })?.pass === true
      setSensors((prev) =>
        prev.map((r, j) => (j === i ? { ...r, status: pass ? 'pass' : 'fail' } : r))
      )
    } catch {
      setSensors((prev) => prev.map((r, j) => (j === i ? { ...r, status: 'fail' } : r)))
    }
  }

  async function finish() {
    setSaving(true)
    setError(null)
    try {
      const agentsRes = await invoke('foundry:agents-md-write', {
        workspaceRoot: repoRoot,
        content: agentsMd,
      })
      if ('error' in agentsRes) throw new Error(agentsRes.error as string)

      const harnessRes = await invoke('foundry:harness-write', {
        workspaceRoot: repoRoot,
        harness: {
          version: 1,
          sensors: sensors
            .filter((s) => s.name.trim() && s.command.trim())
            .map((s) => ({ name: s.name.trim(), command: s.command.trim() })),
          gateDefaults: {
            requireGateAfterEachIteration: true,
            sensorsMustPassBeforeGate: true,
            autoCheckpointBeforeRun: true,
            requireCleanWorkingTree: true,
          },
          providerRef: { providerId: provider },
          iterationLimit: 3,
          agentsMdPath: 'AGENTS.md',
        },
      })
      if ('error' in harnessRes) throw new Error(harnessRes.error as string)
      setStep('done')
    } catch (err) {
      setError(String(err))
    } finally {
      setSaving(false)
    }
  }

  function next() {
    const ni = stepIdx + 1
    if (ni < STEPS.length - 1) setStep(STEPS[ni])
    else void finish()
  }

  const isLastStep = stepIdx === STEPS.indexOf('provider')

  return (
    <div className="fnd-wizard">
      {/* Header */}
      <div className="fnd-wizard-header">
        <span className="fnd-wizard-title">Set up your harness</span>
        <button className="fnd-wizard-close" onClick={onCancel}>
          ×
        </button>
      </div>

      {/* Step bar */}
      <div className="fnd-step-bar">
        {STEPS.filter((s) => s !== 'done').map((s, i) => {
          const isDone = STEPS.indexOf(s) < stepIdx
          const isActive = s === step
          const cls = isDone
            ? 'fnd-step fnd-step--done'
            : isActive
              ? 'fnd-step fnd-step--active'
              : 'fnd-step fnd-step--idle'
          return (
            <React.Fragment key={s}>
              {i > 0 && <div className="fnd-step-line" />}
              <div className={cls}>
                <div className="fnd-step-num">{isDone ? '✓' : i + 1}</div>
                <span>{STEP_LABELS[s]}</span>
              </div>
            </React.Fragment>
          )
        })}
      </div>

      {/* Body */}
      <div className="fnd-wizard-body">
        {step === 'done' ? (
          <div className="fnd-done">
            <div className="fnd-done-icon">✓</div>
            <div className="fnd-done-title">Harness ready</div>
            <div className="fnd-done-sub">
              AGENTS.md and .foundry/harness.json
              <br />
              have been written to your workspace.
            </div>
            <button className="fnd-btn fnd-btn--primary" onClick={onComplete}>
              Open Foundry
            </button>
          </div>
        ) : step === 'template' ? (
          <TemplateStep selected={selectedTemplate} onSelect={pickTemplate} />
        ) : step === 'agents-md' ? (
          <AgentsMdStep
            content={agentsMd}
            onChange={setAgentsMd}
            template={selectedTemplate}
            onTemplateChange={pickTemplate}
          />
        ) : step === 'sensors' ? (
          <SensorsStep
            sensors={sensors}
            onUpdate={updateSensor}
            onAdd={() => setSensors((p) => [...p, { name: '', command: '', status: 'unchecked' }])}
            onRemove={(i) => setSensors((p) => p.filter((_, j) => j !== i))}
            onCheck={checkSensor}
          />
        ) : (
          <ProviderStep selected={provider} onSelect={setProvider} />
        )}
      </div>

      {/* Error */}
      {error && <div className="fnd-error-bar">{error}</div>}

      {/* Footer */}
      {step !== 'done' && (
        <div className="fnd-wizard-footer">
          <span className="fnd-wizard-footer-hint">
            {step === 'agents-md' && 'AGENTS.md will be written to the workspace root'}
            {step === 'sensors' && 'Sensors are optional — add or edit later in settings'}
            {step === 'provider' && 'API keys can be added in Foundry settings after setup'}
          </span>
          <div className="fnd-wizard-footer-actions">
            {stepIdx > 0 && (
              <button
                className="fnd-btn fnd-btn--secondary fnd-btn--sm"
                onClick={() => setStep(STEPS[stepIdx - 1])}
              >
                Back
              </button>
            )}
            <button
              className="fnd-btn fnd-btn--primary fnd-btn--sm"
              onClick={next}
              disabled={saving}
            >
              {saving ? 'Saving…' : isLastStep ? 'Finish' : 'Next →'}
            </button>
          </div>
        </div>
      )}
    </div>
  )
}

// ─── Step components ──────────────────────────────────────────────────────────

function TemplateStep({ selected, onSelect }: { selected: string; onSelect: (t: string) => void }) {
  return (
    <div style={{ flex: 1, padding: 14 }}>
      <div className="fnd-section-label" style={{ marginBottom: 12 }}>
        Choose a starter template
      </div>
      <div className="fnd-template-grid">
        {Object.keys(TEMPLATES).map((t) => (
          <div
            key={t}
            className={`fnd-template-card${selected === t ? ' fnd-template-card--selected' : ''}`}
            onClick={() => onSelect(t)}
          >
            <div className="fnd-template-name">{t}</div>
            <div className="fnd-template-desc">
              {t === 'TypeScript / Node' && 'npm scripts, ESLint, Vitest patterns'}
              {t === 'General' && 'Standard sections, fill in your stack'}
              {t === 'Python' && 'pytest, ruff, venv patterns'}
              {t === 'Blank' && 'Start from scratch'}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

function AgentsMdStep({
  content,
  onChange,
  template,
  onTemplateChange,
}: {
  content: string
  onChange: (c: string) => void
  template: string
  onTemplateChange: (t: string) => void
}) {
  const [dragging, setDragging] = React.useState(false)

  async function importFile() {
    const res = (await invoke('foundry:open-file', {
      filters: [{ name: 'Markdown / text', extensions: ['md', 'txt', 'mdx'] }],
    })) as Record<string, unknown>
    if ('filePath' in res) {
      const read = (await invoke('foundry:read-file', { filePath: res.filePath })) as Record<
        string,
        unknown
      >
      if ('content' in read) onChange(read.content as string)
    }
  }

  function onDrop(e: React.DragEvent) {
    e.preventDefault()
    setDragging(false)
    const file = e.dataTransfer.files[0]
    if (!file) return
    const p = (file as File & { path?: string }).path
    if (!p) return
    void invoke('foundry:read-file', { filePath: p }).then((res) => {
      if ('content' in res) onChange(res.content as string)
    })
  }

  return (
    <div
      style={{
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        minWidth: 0,
        outline: dragging ? '2px solid var(--tm-accent)' : 'none',
        outlineOffset: -2,
      }}
      onDragOver={(e) => {
        e.preventDefault()
        setDragging(true)
      }}
      onDragLeave={() => setDragging(false)}
      onDrop={onDrop}
    >
      <div className="fnd-editor-toolbar">
        <span className="fnd-editor-label">AGENTS.md {dragging && '— drop to import'}</span>
        <button
          className="fnd-btn fnd-btn--secondary fnd-btn--sm"
          onClick={importFile}
          title="Import from file"
        >
          Import…
        </button>
        <select
          className="fnd-editor-select"
          value={template}
          onChange={(e) => onTemplateChange(e.target.value)}
        >
          {Object.keys(TEMPLATES).map((t) => (
            <option key={t}>{t}</option>
          ))}
        </select>
      </div>
      <textarea
        className="fnd-editor-textarea"
        value={content}
        onChange={(e) => onChange(e.target.value)}
        spellCheck={false}
        placeholder="Drag & drop a file here, or click Import… to load from disk"
      />
    </div>
  )
}

function SensorsStep({
  sensors,
  onUpdate,
  onAdd,
  onRemove,
  onCheck,
}: {
  sensors: SensorRow[]
  onUpdate: (i: number, f: 'name' | 'command', v: string) => void
  onAdd: () => void
  onRemove: (i: number) => void
  onCheck: (i: number) => void
}) {
  return (
    <div style={{ flex: 1, overflow: 'auto', padding: 14 }}>
      <div className="fnd-section-label" style={{ marginBottom: 12 }}>
        Feedback sensors
      </div>
      {sensors.map((s, i) => (
        <div key={i} className="fnd-sensor-card">
          <div className="fnd-sensor-row">
            <input
              className="fnd-sensor-name-input"
              value={s.name}
              onChange={(e) => onUpdate(i, 'name', e.target.value)}
              placeholder="name"
            />
            <SensorStatusBadge status={s.status} />
            <button
              onClick={() => onRemove(i)}
              style={{
                marginLeft: 'auto',
                background: 'none',
                border: 'none',
                color: 'var(--tm-text-secondary)',
                cursor: 'pointer',
                fontSize: 16,
                lineHeight: 1,
                padding: '2px 4px',
                borderRadius: 'var(--tm-radius-xs)',
              }}
            >
              ×
            </button>
          </div>
          <div style={{ display: 'flex', gap: 6 }}>
            <input
              className="fnd-sensor-cmd-input"
              value={s.command}
              onChange={(e) => onUpdate(i, 'command', e.target.value)}
              placeholder="command (e.g. npm run lint)"
            />
            <button
              className="fnd-btn fnd-btn--secondary fnd-btn--sm"
              onClick={() => onCheck(i)}
              disabled={!s.command.trim() || s.status === 'checking'}
            >
              {s.status === 'checking' ? '…' : 'Run'}
            </button>
          </div>
        </div>
      ))}
      <button className="fnd-add-sensor-btn" onClick={onAdd}>
        + Add sensor
      </button>
      <p className="fnd-hint">
        Sensors are optional. You can add or edit them any time in Foundry settings.
      </p>
    </div>
  )
}

function SensorStatusBadge({ status }: { status: SensorStatus }) {
  const labels: Record<SensorStatus, string> = {
    unchecked: 'not checked',
    checking: 'checking…',
    pass: '✓ ok',
    fail: '✗ failed',
  }
  return <span className={`fnd-sensor-status fnd-sensor-status--${status}`}>{labels[status]}</span>
}

function ProviderStep({ selected, onSelect }: { selected: string; onSelect: (p: string) => void }) {
  const providers = [
    { id: 'claude', label: 'Claude (Anthropic)', note: 'API key required' },
    { id: 'openai', label: 'OpenAI', note: 'API key required' },
    { id: 'gemini', label: 'Gemini (Google)', note: 'API key required' },
    { id: 'ollama', label: 'Ollama (local)', note: 'No API key needed' },
  ]
  return (
    <div style={{ flex: 1, padding: 14 }}>
      <div className="fnd-section-label" style={{ marginBottom: 12 }}>
        Default AI provider
      </div>
      {providers.map((p) => (
        <div key={p.id} className="fnd-provider-option" onClick={() => onSelect(p.id)}>
          <span className="fnd-provider-name">{p.label}</span>
          <span className="fnd-provider-note">{p.note}</span>
          <div className={`fnd-radio${selected === p.id ? ' fnd-radio--checked' : ''}`}>
            {selected === p.id && <div className="fnd-radio-dot" />}
          </div>
        </div>
      ))}
      <p className="fnd-hint">API keys are stored in the OS keychain — never written to disk.</p>
    </div>
  )
}
